services:
  postgres:
    image: postgres:latest
    container_name: bank_rest_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_rest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  backend:
    build: .
    container_name: bank_rest_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  pgdata:
